# Generated by Django 4.0.4 on 2023-04-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.TextField(max_length=50),
        ),
    ]
